### ISSUE TITLE
Episode Title in Facebook Media Share

### ISSUE THREAD

**Issue by Dreamfish19** [podlove/podlove-publisher#909] opened 2017-03-31 08:33 UTC
Sharing the podcast with the webplayers "facebook" button, facebook shows "no title" in the share box.
Open graph debugger shows no errors.

![facebook_podcast_share](https://cloud.githubusercontent.com/assets/9974678/24542798/54c105d4-15fd-11e7-95cd-b023f9cbf4cb.png)

Affected page:
http://www.teamact.de/podcast/

### System information (see `Podlove > Support` menu)
Website             http://www.teamact.de
PHP Version         5.6.29-nmm1
WordPress Version   4.7.3
WordPress Theme     FoundationPress v5.5.0
Publisher Version   2.5.0
Web Player Version  2.1.0
Twig Version        1.32.0
open_basedir        /www/htdocs/w0139xxx/:/tmp:/usr/bin:/www/htdocs/w0139xxx:/bin:/usr/local/bin:/usr/share/php:/dev/urandom
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 200M
memory_limit        256M
disable_classes     
disable_functions   exec,system,passthru,shell_exec,popen,escapeshellcmd,proc_open,proc_nice
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg http://www.teamact.de/feed/mp3/
cron                ok

0 errors
1 NOTICE (no dealbreaker, but should be fixed if possible): 
- The PHP setting "open_basedir" is not empty. This is incompatible with curl, a library required by Podlove Publisher. We have a workaround in place but it is preferred to fix the issue. Please ask your hoster to unset "open_basedir".

**Comment by chemiker** [comment] 2017-04-07 14:11
I think this issue is related to several errors in your website's HTML markup (see https://validator.w3.org/check?uri=http%3A%2F%2Fwww.teamact.de%2Ffolge-14-kommunikation-in-konfliktsituationen-fragen-statt-ratschlaege-interview-mit-bernhard-boehm%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). 

I checked if the the "no title" issue is related to the open graph information by the publisher which is not the case. While playing around I noticed that using the information provided by the publisher (Title, Description etc.) the open graph parser "ignores" the information by the publisher and instead catches all required information from the provided open graph URL. I could not figure out why the open graph infos are ignored and instead they catch their own information from the website. It might be that the provided description contained to many special characters or due to any other unknown reason. Interestingly, the observed behavior was not reproducible using a website URL for a different Podlove instance. Thus the issue might be a result of invalid HTML as mentioned above.

I will close this ticket for now since this seems not to be an issue with the publisher. My best guess would be that this issue might be fixed by providing valid HTML. Please let us know if you have any information that proves that the publisher is related to this issue.

**Closed by chemiker** 2017-04-07 14:11 UTC
