### ISSUE TITLE
detect links in shownotes as related episodes

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-publisher#797] opened 2015-11-14 07:43 UTC
Linking [related episodes](https://github.com/podlove/podlove-publisher/commit/1de3e5074ab9a441299f05ec47ec746e92944d05) which were implemented in [v2.3](https://github.com/podlove/podlove-publisher/releases/tag/2.3.0) during the preparation of an episode is no big deal thanks to the intuitive UI. However, going through an episodes archive is a lot more, bit annoying work.

How about an option/function to crawl the HTML show notes & chapters for links to old episodes (or their slugs or mnemonics) and auto-assign them as related?

**Comment by simondueckert** [comment] 2015-11-14 08:02
Perhaps one could use the pingback (self-pings) mechanism of wordpress? I get pingbacks each time I link to one of my episodes in the shownotes. https://en.support.wordpress.com/comments/pingbacks/

**Comment by eteubert** [comment] 2015-11-15 11:42
I'll close this here since it's not a bug report.

Also, I don't think this will find its way into the publisher. I see the use case but it's a rare one.

**Closed by eteubert** 2015-11-15 11:42 UTC
