### ISSUE TITLE
Episode data not stored and no audio files listed

### ISSUE THREAD

**Issue by andibraeu** [podlove/podlove-publisher#1273] opened 2022-02-08 06:33 UTC
### Expected behavior

When I create a new episode, everything is stored: Episode number, title, description, participants, etc. Also the audio files created with auphonic will be detected and included into the episode.

### Actual behavior

Nothing podlove specific will be stored at the moment. I tried both, the classic and the gutenberg editor. An Auphonic production can be started and will finish. Acutally the length of the episode will be detected, but the assets will not be listed there. When I open the browser console I can see that the data is fetched and available.

What I tried so far: First I saw an error that there's a column missing in the database table podlove_episode. I removed the plugin and added it again. Now the column is there. I also changed from Gutenberg to the Classic editor.

All the wordpress default stuff like title and text, publishing date etc. will be stored.

### System information (see `Podlove > Support` menu)
```
Website                    https://domain
PHP Version                7.4.27
WordPress Version          5.9
WordPress Theme            Twenty Eleven v4.0
Active Plugins             
           - TAuto Poster v1.4.6
           - Classic Editor v1.6.2
           - Podlove Podcast Publisher v3.7.2
           - Redirection v5.2.3
           - Shariff Wrapper v4.6.7
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          3.7.2
Publisher Database Version 153
Web Player Version         player_v4
Monolog Version            1
open_basedir               ok
curl Version               7.58.0
iconv                      available
simplexml                  ok
max_execution_time         120
upload_max_filesize        2M
memory_limit               768M
disable_classes            
disable_functions          opcache_get_status
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://domain/feed/mp3/
  - m4a    audio/mp4        no feed
  - ogg    audio/ogg        no feed
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by andibraeu** [comment] 2022-02-08 21:51
In early December I published the last episode of our podcast without any issues.

Yesterday I started to publish the next episode.

The only thing the browser console shows in Classic Editor is 
![image](https://user-images.githubusercontent.com/1162168/153080658-dc0d4f70-c2c7-4b23-988f-aa7b3063c569.png)

After saving, fields for episode number, title etc. are empty again.

Debugging is enabled with 

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```
But nothing shows up in the logs. This installation is a multisite-installation, maybe that's important.

**Comment by andibraeu** [comment] 2022-02-10 09:36
I digged a bit deeper and looked at the POST request sent on saving a preview.

In this POST request all data is sent to the server. So there's no error on the client side.

![image](https://user-images.githubusercontent.com/1162168/153379317-037f577a-3b18-4b74-9e3d-ae64c4a1a195.png)

**Comment by oe1rfc** [comment] 2022-02-10 12:08
Hi,
so, we had the exact same problem, initially I suspected #1265 but this was actually not the root cause.

What actually happened was that the database migration has actually failed, although the Publisher Database Version was incremented.
So every time you try to add a new episode, the wordpress page for the episode was created, but the corresponding podlove_episode could not be inserted, so saving of settings and artifacts fails, because there is no matching episode.

So I think there are two main problems:
- The database migration fails silently and the Publisher Database Version is always updated.
- Insert/Update errors do not produce any error logs, even if WP_DEBUG and WP_DEBUG are set.

It took us a few days of debugging where we verified, that the plugin successfully processed the POST data, but the episode I tried to save was always null.
I was lucky to find this in the last, not-yet-removed, mariadb error logfile, because there were no logged upgrade errors. _(this is a multisite, so 4 instances)_
```
2022-01-23 19:29:37 3034971 [ERROR] InnoDB: Cannot add field `soundbite_duration` in table `wordpress`.`wp_podlove_episode` because after adding it, the row size is 8649 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page.
2022-01-23 19:29:37 3034971 [ERROR] InnoDB: Cannot add field `soundbite_duration` in table `wordpress`.`wp_4_podlove_episode` because after adding it, the row size is 8649 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page.
2022-01-23 19:29:37 3034971 [ERROR] InnoDB: Cannot add field `soundbite_duration` in table `wordpress`.`wp_6_podlove_episode` because after adding it, the row size is 8649 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page.
2022-01-23 19:29:37 3034971 [ERROR] InnoDB: Cannot add field `soundbite_duration` in table `wordpress`.`wp_7_podlove_episode` because after adding it, the row size is 8649 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page.
```
The root cause for this was that this is an older (~4-5y) mariadb installation, where the default for the table row format was still `Compact`.
You can fix this by setting the row format to dynamic:
```
ALTER TABLE wp_podlove_episode ROW_FORMAT=DYNAMIC;
```
and manually re-run the migration commands for the missing rows from: https://github.com/podlove/podlove-publisher/blob/master/lib/version.php#L1585-L1598 (to know which rows are missing run `DESCRIBE TABLE wp_podlove_episode;`)

If you want to know which tables are still Compact:
```
SELECT table_name, row_format FROM information_schema.tables WHERE table_schema=DATABASE() and row_format = ‘Compact’;
```
One option to convert all tables to dynamic is by setting the default to dynamic, which is probably wise:
```
SET GLOBAL innodb_default_row_format='dynamic';
```
And then run an `OPTIMIZE TABLE` for each table. This might take a while for larger tables, and IIRC there is no (simple?) way to run it for a whole database.

**Comment by andibraeu** [comment] 2022-02-10 13:24
thanks @oe1rfc 

with your steps I could solve the problem on my site.

@eteubert should I let this issue open?

**Comment by eteubert** [comment] 2022-02-11 13:04
Oh wow thanks for your digging and the detailed explanation @oe1rfc. I will close this issue and create a separate one. The main issue here is that the Publisher should catch errors during a migration and inform the user.

**Closed by eteubert** 2022-02-11 13:04 UTC
Labels: bug
