### ISSUE TITLE
Podlove crashing woo commerce shop

### ISSUE THREAD

**Issue by pixelcatcher** [podlove/podlove-publisher#1185] opened 2021-01-23 14:13 UTC
### Actual behavior

When a new user signs up in my shop and then visits the verification page

“/my-account/?activated=yes”

Something goes wrong and all shop pages including cart and my account generate error 404. This can be resolved by refreshing permalinks.

Thats crazy enough – but it only happens when podlove plugin is active.
I want to keep using this plugin but I don’t see how as long as it keeps breaking my shop.

any ideas?

### System information (see `Podlove > Support` menu)

Website                    https://www.pixelcatcher.de
PHP Version                7.4.10
WordPress Version          5.6
WordPress Theme            Photography v6.7.1
Active Plugins             
           - WPML Multilingual CMS v4.4.8
           - 404page - deine maßgeschneiderte 404-Fehlerseite v11.3.0
           - Add From Server v3.4.5
           - Better Search Replace  v1.3.4
           - Borlabs Cookie - Cookie Opt-in v2.2.13
           - Contact Form 7 Multilingual v1.0.2
           - Contact Form 7 v5.3.2
           - WooCommerce Coupon Generator v1.1.0
           - Customizer Export/Import v0.9.2
           - Disable Author Archives v1.2.1
           - Yoast Duplicate Post v4.0.2
           - Easy Theme and Plugin Upgrades v2.0.1
           - Finale - WooCommerce Sales Countdown Timer & Discount Plugin v2.17.1
           - Flexible Checkout Fields v2.9.1
           - Force Regenerate Thumbnails v2.0.6
           - GetResponse for WordPress v5.5.9
           - Header Footer Code Manager v1.1.8
           - MAK WooCommerce Download Permissions v3.1.2
           - Meta Generator and Version Info Remover v11.0
           - My Custom Functions v4.48
           - NinjaFirewall (WP Edition) v4.3.1
           - NinjaScanner v3.0.2
           - No Category Base (WPML) v1.3
           - Photography Theme Custom Post Type v4.5
           - Podlove Podcast Publisher v3.2.2
           - PW WooCommerce Gift Cards v1.170
           - Really Simple SSL v4.0.6
           - Redirection v5.0
           - Rank Math SEO v1.0.56.1
           - Simple Custom CSS v4.0.4
           - Simple Post Type Permalinks v2.0.5
           - Sitewide Notice WP v2.2.1
           - WooCommerce Thank You Page - NextMove v1.14.0
           - Twenty20 Image Before-After v1.5.7
           - Vendidero Helper v1.3.0
           - Woo Coupon URL v1.0.0
           - NextMove Lite - Thank You Page for WooCommerce v2.13.1
           - Direct Checkout for WooCommerce v2.4.3
           - Germanized für WooCommerce Pro v3.1.3
           - Germanized für WooCommerce v3.3.4
           - WooCommerce Multilingual v4.10.4
           - WooCommerce Product SKU Generator v2.4.5
           - WooCommerce Sequential Order Numbers v1.9.5
           - WooCommerce v4.9.1
           - AeroCheckout: Custom WooCommerce Checkout Pages v2.3.0
           - CartHopper: WooCommerce Skip Cart v1.0.0
           - OrderBumps: WooCommerce Checkout Offers v1.9.1
           - UpStroke: WooCommerce One Click Upsells v2.2.9
           - UpStroke: WooCommerce Reports v1.5.0
           - Asset CleanUp Pro: Page Speed Booster v1.1.8.7
           - WP Clean Admin Menu v1.1
           - Multi-Step Checkout for WooCommerce v2.14
           - WP-Optimize - Clean, Compress, Cache v3.1.6
           - WPML Media v2.6.2
           - WPML String Translation v3.1.6
           - WPML Translation Management v2.10.4
           - XL WooCommerce Sales Triggers v2.10.0
WordPress Database Charset DB_CHARSET
WordPress Database Collate DB_COLLATE
Publisher Version          3.2.2
Web Player Version         player_v4
Monolog Version            1
open_basedir               ok
curl Version               7.68.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        200M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://www.pixelcatcher.de/feed/coffee-and-cameras-podcast-michael-damboeck/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment] 2021-04-05 19:47
Closing because likely duplicate of #1038

**Closed by eteubert** 2021-04-05 19:47 UTC
