### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ednyfed** [podlove/podlove-publisher#1040] opened 2019-03-22 21:44 UTC
### Expected behavior
When I go to the podcast landing page I should see my episodes.

### Actual behavior
Instead I receive the following (same as when I attempt to edit or create an episode)

Fatal error: Declaration of Twig_Extensions_TokenParser_Trans::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $token) in /homepages/0/d292141472/htdocs/clickandbuilds/KolTikvah/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/twig/extensions/lib/Twig/Extensions/TokenParser/Trans.php on line 86

URL: https://koltikvahdayton.com/messages-2/messages

### System information (see `Podlove > Support` menu)

Website                    https://koltikvahdayton.com
PHP Version                7.2.16
WordPress Version          5.1.1
WordPress Theme            Nirvana v1.5.1.1
Active Plugins             
           - WP Assistant v5.2.0
           - Akismet Anti-Spam v4.1.1
           - All In One WP Security v4.3.8.3
           - BackWPup v3.6.8
           - Broken Link Checker v1.11.8
           - Contact Form 7 v5.1.1
           - Cryout Serious Theme Settings v0.5.9
           - Display Posts v3.0.1
           - Elementor v2.5.9
           - Flamingo v1.9
           - Jetpack by WordPress.com v7.1.1
           - MailPoet 3 (New) v3.21.1
           - Podlove Podcast Publisher v2.7.23
           - Podlove Subscribe Button v1.3.6
           - Podlove Web Player v2.1.0
           - Statify v1.6.3
           - TinyMCE Advanced v5.1.0
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.23
Web Player Version         player_v4
Twig Version               1.38.0
open_basedir               ok
curl Version               7.38.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        67108864
memory_limit               268435456
disable_classes            
disable_functions          
permalinks                 ok (/%postname%)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://koltikvahdayton.com/feed/mp3
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment] 2019-03-23 13:45
Duplicate of #1039. Disabling MailPoet might fix the issue until MailPoet is updated.

**Closed by eteubert** 2019-03-23 13:45 UTC

**Comment by ednyfed** [comment] 2019-03-23 14:00
Confirmed - disabling MailPoet corrected the issue
