### ISSUE TITLE
Supporting podcastindex.org namespaces

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-publisher#1166] opened 2020-10-19 13:01 UTC
Podcastindex.org tries to implement generic rules for namespaces, e.g. transcripts etc. Perhaps it would be good supporting these namespaces for the podlove feeds:
https://github.com/Podcastindex-org/podcast-namespace

**Comment by eteubert** [comment] 2021-04-05 19:48
Closing because the issue is too generic to be useful / impossible to "finish". But yes, I'll keep working on supporting podcastindex.org specs :)

**Closed by eteubert** 2021-04-05 19:49 UTC
