### ISSUE TITLE
Podlove Subscribe Button doesn't show app selection

### ISSUE THREAD

**Issue by David1701** [podlove/podlove-publisher#731] opened 2015-04-25 22:04 UTC
The button "App auswählen" (Select app?) doesn't react. No selection is shown. I tested on Mac Safari and Chrome as well as on iOS Safari and Chrome. Site: unser-podcast.de. The button works properly on my other podcast schwarmtaler.de.

Website             http://unser-podcast.de
PHP Version         5.5.22
WordPress Version   4.1
Publisher Version   2.1.0
Web Player Version  2.0.17
open_basedir        ok
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  0
upload_max_filesize 32M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok
podcast_settings    
web_player          ok
podlove_cache       on
assets              
	mp4    video/mp4

0 errors
0 notices
Nice, Everything looks fine!

**Comment by timpritlove** [comment] 2015-04-25 22:10
Error in JavaScript console reads:

[Error] TypeError: undefined is not an object (evaluating 'r.replace')
	prepareClients (app.js, line 1)
	e (app.js, line 1)
	initPanels (app.js, line 1)
	t (app.js, line 1)
	openPopup (app.js, line 1)
	(anonymous function) (app.js, line 1)
	(anonymous function) (app.js, line 1)

**Comment by eteubert** [comment] 2015-04-27 01:30
The button doesn't handle video yet. 
Closing because duplicate of https://github.com/podlove/podlove-subscribe-button/issues/46

**Closed by eteubert** 2015-04-27 01:30 UTC
