### ISSUE TITLE
Hebrew: subtitle/summary encoding issue

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-publisher#666] opened 2015-02-18 13:00 UTC
Not sure yet if the Publisher or the Player are broken.

> I'm having trouble with Hebrew characters in episode summary and description. Shows question marks. Funnily, title works just fine.
> Screenshot: http://imgur.com/Y2yIc44

From https://wordpress.org/support/topic/character-encoding-in-summary-and-description-h?replies=1#post-6579957

**Comment by chemiker** [comment] 2017-04-10 19:13
@eteubert Is this still an issue and a duplicate of #629?

**Comment by eteubert** [comment] 2017-04-11 08:26
Might be a duplicate but needs to be tested.

Todo: Verify if issue persists with [utf8mb4](https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/) encoded tables.

**Comment by chemiker** [comment] 2017-04-14 15:02
@eteubert I just checked (String: "עִבְרִי‎") if this issue persists with "utf8" encoded tables (Collation: utf8_general_ci) which is **not** the case! Search results were fine, too (see #629).

**Comment by chemiker** [comment] 2017-04-14 17:05
This issue is most likely a result of databases created with a non >=UTF-8 charset. Since the publisher creates databases with an UTF-8 charset for a while, most instances of the Publisher are not affected.

It is worth mentioning that a [recent WordPress Update](https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/) may also resolve this issue.

However, we will add additional details on charset and collation to our system report to track down charset related issues more easily.

**Closed by chemiker** 2017-04-14 17:05 UTC
Labels: bug
