### ISSUE TITLE
Cannot delete or edit shows

### ISSUE THREAD

**Issue by Biofunk** [podlove/podlove-publisher#1077] opened 2019-11-01 14:01 UTC
### Actual behavior
I cannot delete or edit my shows. When I click on "edit show" the wrong show is shown or data is missing. 

### System information (see `Podlove > Support` menu)
Website                    https://www.biofunk.net
PHP Version                7.3.11
WordPress Version          5.2.4
WordPress Theme            Toujours v1.1.0
Active Plugins             
           - Podlove Podcast Publisher v2.9.5
           - Podlove Subscribe Button v1.3.7
           - Podlove Web Player v2.1.0
           - WPForms Lite v1.5.5.1
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.9.5
Web Player Version         player_v4
Twig Version               1.42.2
open_basedir               ok
curl Version               7.58.0
iconv                      available
simplexml                  ok
max_execution_time         50
upload_max_filesize        96M
memory_limit               2147483648
disable_classes            
disable_functions          disk_total_space, diskfreespace, exec, system, popen, proc_open, proc_nice, shell_exec, passthru, dl
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://www.biofunk.net/feed/mp3/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by SaschaRu** [comment] 2020-09-01 12:33
Same here. 

Website                    https://www.trailrunnersdog.de
PHP Version                7.3.21
WordPress Version          5.5
WordPress Theme            Uku Child v1.3.7.1570645968
Active Plugins             
           - VaultPress v2.1.4
           - 2FAS Light — Google Authenticator v2.0
           - AdSense In-feed Placement for WordPress v1.1.1
           - Advanced Ads v1.19.1
           - Antispam Bee v2.9.2
           - Better Notifications for WP v1.8.4
           - Easy Table of Contents v2.0.11
           - Encyclopedia Pro v1.6.31.1
           - fyyd podcast shortcodes v0.3.1
           - Site Kit by Google v1.15.0
           - (Simply) Guest Author Name v4.20
           - OMGF v3.8.2
           - Hummingbird v2.5.1
           - Podlove Podcast Publisher v2.11.4
           - Podlove Web Player v5.2.9
           - Redirection v4.8
           - Shariff Wrapper v4.6.5
           - Simple History v2.36.0
           - The Events Calendar: Filter Bar v4.10.2
           - The Events Calendar v5.1.6
           - The Events Calendar Extension: Events Control v1.3.0
           - Ultimate Add-Ons für Gutenberg v1.17.0
           - Yoast SEO v14.9
           - WP Last Modified Info v1.7.2
           - WP Product Review Lite v3.7.11
           - WPFront Scroll Top v2.0.2
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.11.4
Web Player Version         player_v5
Twig Version               1.42.2
Monolog Version            1
open_basedir               /var/www/vhosts/trailrunnersdog.de/:/tmp/
curl Version               7.47.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        2M
memory_limit               256M
disable_classes            
disable_functions          opcache_get_status
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://www.trailrunnersdog.de/feed/mp3/
  - chapters.txttext/plain       no feed
  - jpg    image/jpeg       no feed
  - vtt    text/vtt         no feed
  - opus   audio/ogg;codecs=opushttps://www.trailrunnersdog.de/feed/opus/
  - m4a    audio/mp4        https://www.trailrunnersdog.de/feed/aac/
cron                       ok
duplicate_guids            ok

0 errors
1 HINWEIS (no dealbreaker, but should be fixed if possible): 
- The PHP setting "open_basedir" is not empty. This is incompatible with curl, a library required by Podlove Publisher. We have a workaround in place but it is preferred to fix the issue. Please ask your hoster to unset "open_basedir".

**Comment by eteubert** [comment] 2020-09-09 20:13
I keep getting this bug report occasionally but was not able to reproduce it locally.

If anyone with that bug would like to give me WordPress admin access and database access so I can trace it, please send credentials to eric@podlove.org 🙏🏻

**Comment by SaschaRu** [comment] 2020-09-22 08:46
Hallo Eric,

danke für deine Antwort. Was genau benötigst du von mir? Einen Admin zum WordPress und einen separaten DB User?

Gruß
Sascha

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Eric Teubert<mailto:notifications@github.com>
Gesendet: Mittwoch, 9. September 2020 22:13
An: podlove/podlove-publisher<mailto:podlove-publisher@noreply.github.com>
Cc: SaschaRu<mailto:sascha.rupp@hotmail.de>; Manual<mailto:manual@noreply.github.com>
Betreff: Re: [podlove/podlove-publisher] Cannot delete or edit shows (#1077)


I keep getting this bug report occasionally but was not able to reproduce it locally.

If anyone with that bug would like to give me WordPress admin access and database access so I can trace it, please send credentials to eric@podlove.org<mailto:eric@podlove.org> 🙏🏻

**Comment by eteubert** [comment] 2020-09-22 08:57
@SaschaRu Genau, das wäre super. Bitte an eric@podlove.org

**Closed** 2020-09-26 10:27 UTC
Labels: bug
