### ISSUE TITLE
Search with hebrew characters is broken

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-publisher#629] opened 2015-01-16 02:10 UTC
> Once the plugin is activated, the internal Wordpress search function returns zero results when the search term contains Hebrew characters. Once the plugin is off, search works great with Hebrew characters.

from https://wordpress.org/support/topic/plugin-breaks-wp-search-if-containing-hebrew-characters?replies=1#post-6431006

**Comment by eteubert** [comment] 2017-04-11 08:26
Todo: Verify if issue persists with [utf8mb4](https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/) encoded tables.

**Comment by chemiker** [comment] 2017-04-14 17:05
Duplicate of #666. See #666 for more information.

**Closed by chemiker** 2017-04-14 17:05 UTC
Labels: bug
