### ISSUE TITLE
Posts don't behave as expected

### ISSUE THREAD

**Issue by MsMiharo** [podlove/podlove-publisher#991] opened 2018-08-14 08:00 UTC
### Expected behavior
Posts to be published as regular blog posts.

### Actual behavior
Posts being published in different ways, either removing panels and acting as a new page: http://maktsalongen.se/birgitta-ohlsson-kom-forandrade-gick/ or not including the text and images at all: http://maktsalongen.se/veronica-palm/

### System information (see `Podlove > Support` menu)
Website                    http://maktsalongen.se/app
PHP Version                5.6.36
WordPress Version          4.8.7
WordPress Theme             v0.1
Active Plugins             
           - Advanced Custom Fields: Repeater Field v2.0.1
           - Advanced Custom Fields: Nav Menu Field v2.0.0
           - Advanced Custom Fields v4.4.12
           - Backup by BlogVault v1.49
           - Contact Form 7 v4.9.1
           - Duplicator v1.2.30
           - Flamingo v1.7
           - Insert Headers and Footers v1.4.2
           - Podlove Podcast Publisher v2.7.9
           - WordPress Post Type Archive Links v1.3.1
           - WordPress-importör v0.6.3
           - WP DB Driver v2.1.0
           - WP User Avatar v2.0.9
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.9
Web Player Version         player_v4
Twig Version               1.35.3
open_basedir               ok
curl Version               7.58.0
iconv                      available
simplexml                  ok
max_execution_time         50
upload_max_filesize        96M
memory_limit               512M
disable_classes            
disable_functions          disk_total_space, diskfreespace, exec, system, popen, proc_open, proc_nice, shell_exec, passthru, dl
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://maktsalongen.se/feed/mp3/
cron                       ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment] 2018-08-14 08:45
I assume that when you talk about "posts" you mean "episodes".

Indeed, episodes are published as what WordPress calls "custom post type" of type `podcast`. It is up to the theme to treat them different or identical to native posts.

**Comment by eteubert** [comment] 2018-08-14 08:46
closing because this is not a bug

**Closed** 2018-08-14 08:45 UTC
Labels: support
