### ISSUE TITLE
Import leaves off latest episode

### ISSUE THREAD

**Issue by stevenproctor** [podlove/podlove-publisher#813] opened 2015-12-17 15:42 UTC
I am trying to move my wordpress hosting to a new server, so I did a Wordpress import followed by a Podlove `Podcast Data` import.

It the dashboard on the current site shows 39 episodes, but after an import it shows only 38 episodes as active, and the last episode is not included.

If I go into the `Episodes` menu it tells me there are 39 posts for episodes, and if I look at the last episode, the slug for the episode originally matched the URL slug, but not the slug as it exists in the original site for the `Episode Media File Slug` input field, and if I look at the last episode, the `Episode Media File Slug` was imported correctly.

If I manually change it it then shows up correctly in the dashboard and everything now shows up.

Thanks for your help.

```
Website             http://159.203.100.165
PHP Version         5.5.9-1ubuntu4.14
WordPress Version   4.4
Publisher Version   2.3.6
Web Player Version  2.0.19
Twig Version        1.23.1
open_basedir        ok
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 2M
memory_limit        256M
disable_classes     
disable_functions   pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks          ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
	mp3    audio/mpeg

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by stevenproctor** [comment] 2015-12-18 05:48
It did the same for the Podcast Analytics as well too... ;(

Which means I likely lost all of my stats for the most recent episode.

**Comment by eteubert** [comment] 2015-12-18 09:05
Is it possible that you used the WordPress Exporter before publishing the last episode?

It might be to late for this tip but for moving a whole WordPress instance to another server, the https://wordpress.org/plugins/duplicator/ plugin is a great tool.

**Comment by eteubert** [comment] 2016-01-08 09:21
I can't reproduce it locally. I close it but will reopen if more information is provided.

**Closed by eteubert** 2016-01-08 09:21 UTC

**Comment by stevenproctor** [comment] 2016-02-09 04:55
@eteubert I put the releasing of episodes on "pause" for a few weeks as I just had a new baby, and went back to try to update the "missing" stats by stitching the old export and the new export together. This didn't take with what I was doing, so I just imported the file I exported about 30 minutes before, and I can see a difference in the stats there even.


Before:

![screen shot 2016-02-08 at 10 15 24 pm](https://cloud.githubusercontent.com/assets/509982/12907814/75238ecc-ceb5-11e5-9951-d047ffbf1910.png)

After:
![screen shot 2016-02-08 at 10 36 26 pm](https://cloud.githubusercontent.com/assets/509982/12907815/752615b6-ceb5-11e5-895e-06aeb0969fa6.png)

Github doesn't let me attach the file, but I would be happy to send you the export result if that would help troubleshoot.

As a side note, I wondered if it was because the times in the CSV look to be in UTC, but my Wordpress install is set to Chicago, so I updated the Wordpress time setting in General to be set to UTC, but I don't know if that would make a difference, as the server time is set to EST anyway, but it didn't seem to make a difference in the result.

Thanks

**Comment by stevenproctor** [comment] 2016-02-09 06:49
Looking into this further, I see that there is something about cleaning up intents: https://github.com/podlove/podlove-publisher/blob/3a976cb6c917242c7eb3ae65385d478707bc296e/lib/analytics/download_intent_cleanup.php#L23


But it still seems odd that I loose that much downloads across the two different imports, originally and this recent export/import process.

hLooking at that code, it looks like It does the grouping by the request id (which I don't know how that gets calcuated at this point) and date to the hour.  I am wondering if that the right scale if the agent is the same for all requests from the same podcatcher across devices (e.g. doggcatcher, overcast, downcast, etc) and there are a number of different devices that try to download all in the same hour.

Again, this may be caught by the request id, but it is way late for me at this point in the night so I will have to continue looking at another point.

Thanks for your help in advance!!!!

**Comment by eteubert** [comment] 2016-02-09 09:29
Regarding the request id: http://docs.podlove.org/podlove-publisher/guides/download-analytics.html#request-id

> The request ID is an artificial compound ID to identify identical requests anonymously. It is a hash from the combined IP address and user agent string.

We are using this to get rid of duplicates. I don't think our scale of grouping is too broad.

Regarding the difference in numbers: It *might* be a better bot detection (I update the user agent library only occasionally and don't recalculate all analytics when I do it).
The server time *should* not make a difference.

One thing you could do: In your old database, export/backup the `wp_podlove_downloadintentclean` table, then empty it. After a while (max. 1 hour) the Publisher should detect that it has to recalculate the data and regenerate all tracking data based off the raw data. Then you can compare the results.

**Comment by stevenproctor** [comment] 2016-02-16 03:48
Thanks for the clarification!
